collections:
        authors:
                output: true

baseurl: ""
url: "https://gyfu.github.io/verkefni5/"
permalink: /:title

defaults:
  - scope:
      path: ""
      type: "authors"
    values:
      layout: "author"
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
  - scope:
      path: ""
    values:
      layout: "default"
