collections:
        authors:
                output: true
                url: "https://gyfu.github.io"
                baseurl: "/verkefni5"
defaults:
  - scope:
      path: ""
      type: "authors"
    values:
      layout: "author"
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
  - scope:
      path: ""
    values:
      layout: "default"
  - scope: 
    path: "assets/myndir"
    values: 
    image: True
